// <auto-generated />
using System;
using ExamProctoring.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExamProctoring.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExamProctoring.Domain.Entities.AlertEvent", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("alert_type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("created_by")
                        .HasColumnType("int");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("deleted_by")
                        .HasColumnType("int");

                    b.Property<DateTime?>("delivered_at")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("monitoring_event_id")
                        .HasColumnType("int");

                    b.Property<string>("severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("snapshot_url")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("student_session_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("triggered_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("updated_by")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("monitoring_event_id");

                    b.HasIndex("student_session_id");

                    b.ToTable("AlertEvent", (string)null);
                });

            modelBuilder.Entity("ExamProctoring.Domain.Entities.AttemptQuestion", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("created_by")
                        .HasColumnType("int");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("deleted_by")
                        .HasColumnType("int");

                    b.Property<bool>("is_deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("marks")
                        .HasColumnType("int");

                    b.Property<int>("ordinal")
                        .HasColumnType("int");

                    b.Property<Guid>("public_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("question_id")
                        .HasColumnType("int");

                    b.Property<string>("stem")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("student_session_id")
                        .HasColumnType("int");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("updated_by")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("question_id");

                    b.HasIndex("student_session_id", "ordinal");

                    b.HasIndex("student_session_id", "public_id")
                        .IsUnique();

                    b.HasIndex("student_session_id", "question_id")
                        .IsUnique();

                    b.ToTable("AttemptQuestion", (string)null);
                });

            modelBuilder.Entity("ExamProctoring.Domain.Entities.AttemptQuestionOption", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("attempt_question_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("created_by")
                        .HasColumnType("int");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("deleted_by")
                        .HasColumnType("int");

                    b.Property<bool>("is_deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("label")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("ordinal")
                        .HasColumnType("int");

                    b.Property<Guid>("public_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("source_slot")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("updated_by")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("attempt_question_id", "ordinal");

                    b.HasIndex("attempt_question_id", "public_id")
                        .IsUnique();

                    b.ToTable("AttemptQuestionOption", (string)null);
                });

            modelBuilder.Entity("ExamProctoring.Domain.Entities.AuditLog", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("actor_id")
                        .HasColumnType("int");

                    b.Property<string>("actor_type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("created_by")
                        .HasColumnType("int");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("deleted_by")
                        .HasColumnType("int");

                    b.Property<string>("details")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("entity_id")
                        .HasColumnType("int");

                    b.Property<string>("entity_type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("exam_session_id")
                        .HasColumnType("int");

                    b.Property<bool>("is_deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("occurred_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("updated_by")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("exam_session_id");

                    b.ToTable("AuditLog", (string)null);
                });

            modelBuilder.Entity("ExamProctoring.Domain.Entities.AutoScore", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("correct_answer")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("created_by")
                        .HasColumnType("int");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("deleted_by")
                        .HasColumnType("int");

                    b.Property<bool>("is_deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("marks_awarded")
                        .HasColumnType("int");

                    b.Property<int>("max_marks")
                        .HasColumnType("int");

                    b.Property<int>("question_id")
                        .HasColumnType("int");

                    b.Property<string>("student_answer")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("student_session_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("updated_by")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("question_id");

                    b.HasIndex("student_session_id", "question_id")
                        .IsUnique();

                    b.ToTable("AutoScore", (string)null);
                });

            modelBuilder.Entity("ExamProctoring.Domain.Entities.ConnectivityBuffer", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("buffer_type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("buffered_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("created_by")
                        .HasColumnType("int");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("deleted_by")
                        .HasColumnType("int");

                    b.Property<string>("encrypted_payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is_deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("student_session_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("synced_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("updated_by")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("student_session_id");

                    b.ToTable("ConnectivityBuffer", (string)null);
                });

            modelBuilder.Entity("ExamProctoring.Domain.Entities.DeviceCheck", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("checked_at_utc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("client_can_proceed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("created_by")
                        .HasColumnType("int");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("deleted_by")
                        .HasColumnType("int");

                    b.Property<string>("device_id")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("exam_session_status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("is_deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("received_at_utc")
                        .HasColumnType("datetime2");

                    b.Property<int>("student_session_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("updated_by")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("student_session_id", "received_at_utc");

                    b.ToTable("DeviceCheck", (string)null);
                });

            modelBuilder.Entity("ExamProctoring.Domain.Entities.DeviceCheckRequirement", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("created_by")
                        .HasColumnType("int");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("deleted_by")
                        .HasColumnType("int");

                    b.Property<string>("detail")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("device_check_id")
                        .HasColumnType("int");

                    b.Property<bool>("is_deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("requirement_id")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("updated_by")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("device_check_id");

                    b.HasIndex("requirement_id", "status");

                    b.ToTable("DeviceCheckRequirement", (string)null);
                });

            modelBuilder.Entity("ExamProctoring.Domain.Entities.ExamSession", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime?>("active_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("archived_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("closed_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("course_tag")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("created_by")
                        .HasColumnType("int");

                    b.Property<int>("created_by_admin_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("deleted_by")
                        .HasColumnType("int");

                    b.Property<int>("duration_minutes")
                        .HasColumnType("int");

                    b.Property<int>("extended_by_minutes")
                        .HasColumnType("int");

                    b.Property<int>("eye_gaze_threshold_sec")
                        .HasColumnType("int");

                    b.Property<string>("face_alert_sensitivity")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("grace_period_ended_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("grace_period_minutes")
                        .HasColumnType("int");

                    b.Property<bool>("is_deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("locked_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("login_window_minutes")
                        .HasColumnType("int");

                    b.Property<int>("question_bank_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("scheduled_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("start_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("updated_by")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("created_by_admin_id");

                    b.HasIndex("question_bank_id");

                    b.ToTable("ExamSession", (string)null);
                });

            modelBuilder.Entity("ExamProctoring.Domain.Entities.GradingExport", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("created_by")
                        .HasColumnType("int");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("deleted_by")
                        .HasColumnType("int");

                    b.Property<int>("exam_session_id")
                        .HasColumnType("int");

                    b.Property<string>("file_path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("format")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("generated_at")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("updated_by")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("exam_session_id");

                    b.ToTable("GradingExport", (string)null);
                });

            modelBuilder.Entity("ExamProctoring.Domain.Entities.IdempotencyRecord", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("created_at_utc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("created_by")
                        .HasColumnType("int");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("deleted_by")
                        .HasColumnType("int");

                    b.Property<string>("endpoint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("idempotency_key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("is_deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<byte[]>("request_hash")
                        .IsRequired()
                        .HasColumnType("varbinary(32)");

                    b.Property<string>("resource_key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("response_body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("response_status")
                        .HasColumnType("int");

                    b.Property<int>("student_session_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("updated_by")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("student_session_id", "idempotency_key")
                        .IsUnique();

                    b.ToTable("IdempotencyRecord", (string)null);
                });

            modelBuilder.Entity("ExamProctoring.Domain.Entities.IdentityVerificationAttempt", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("attempt_number")
                        .HasColumnType("int");

                    b.Property<DateTime>("attempted_at_utc")
                        .HasColumnType("datetime2");

                    b.Property<int>("attempts_remaining_after")
                        .HasColumnType("int");

                    b.Property<DateTime?>("captured_at_utc")
                        .HasColumnType("datetime2");

                    b.Property<string>("client_attempt_id")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("created_by")
                        .HasColumnType("int");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("deleted_by")
                        .HasColumnType("int");

                    b.Property<string>("embedding_model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("embedding_model_version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("identity_verification_session_id")
                        .HasColumnType("int");

                    b.Property<bool>("is_deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("liveness_accepted")
                        .HasColumnType("bit");

                    b.Property<int>("liveness_blink_count")
                        .HasColumnType("int");

                    b.Property<int>("liveness_duration_ms")
                        .HasColumnType("int");

                    b.Property<int>("liveness_frames_analysed")
                        .HasColumnType("int");

                    b.Property<double>("liveness_max_eye_openness")
                        .HasColumnType("float");

                    b.Property<double>("liveness_min_eye_openness")
                        .HasColumnType("float");

                    b.Property<string>("liveness_rejection_reason")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double?>("match_score")
                        .HasColumnType("float");

                    b.Property<string>("outcome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<double?>("threshold_used")
                        .HasColumnType("float");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("updated_by")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("identity_verification_session_id", "attempted_at_utc");

                    b.HasIndex("identity_verification_session_id", "client_attempt_id")
                        .IsUnique();

                    b.ToTable("IdentityVerificationAttempt", (string)null);
                });

            modelBuilder.Entity("ExamProctoring.Domain.Entities.IdentityVerificationSession", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("attempts_used")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("created_by")
                        .HasColumnType("int");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("deleted_by")
                        .HasColumnType("int");

                    b.Property<string>("device_id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<bool>("is_deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("max_attempts")
                        .HasColumnType("int");

                    b.Property<Guid>("public_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("student_session_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("updated_by")
                        .HasColumnType("int");

                    b.Property<DateTime?>("verified_at_utc")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("public_id")
                        .IsUnique();

                    b.HasIndex("student_session_id")
                        .IsUnique();

                    b.ToTable("IdentityVerificationSession", (string)null);
                });

            modelBuilder.Entity("ExamProctoring.Domain.Entities.MonitoringEvent", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("created_by")
                        .HasColumnType("int");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("deleted_by")
                        .HasColumnType("int");

                    b.Property<string>("event_details")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("event_type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("is_deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("occured_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("student_session_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("updated_by")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("student_session_id");

                    b.ToTable("MonitoringEvent", (string)null);
                });

            modelBuilder.Entity("ExamProctoring.Domain.Entities.Permission", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("created_by")
                        .HasColumnType("int");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("deleted_by")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("is_deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("updated_by")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("name")
                        .IsUnique();

                    b.ToTable("Permission", (string)null);
                });

            modelBuilder.Entity("ExamProctoring.Domain.Entities.PermissionRole", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("created_by")
                        .HasColumnType("int");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("deleted_by")
                        .HasColumnType("int");

                    b.Property<bool>("is_deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("permission_id")
                        .HasColumnType("int");

                    b.Property<int>("role_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("updated_by")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("permission_id");

                    b.HasIndex("role_id");

                    b.ToTable("Permission_Role", (string)null);
                });

            modelBuilder.Entity("ExamProctoring.Domain.Entities.ProctorAction", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("acted_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("action_note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("action_type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("admin_id")
                        .HasColumnType("int");

                    b.Property<int>("alert_event_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("created_by")
                        .HasColumnType("int");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("deleted_by")
                        .HasColumnType("int");

                    b.Property<bool>("is_deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("updated_by")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("admin_id");

                    b.HasIndex("alert_event_id");

                    b.ToTable("ProctorAction", (string)null);
                });

            modelBuilder.Entity("ExamProctoring.Domain.Entities.ProctorSession", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("created_by")
                        .HasColumnType("int");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("deleted_by")
                        .HasColumnType("int");

                    b.Property<int>("exam_session_id")
                        .HasColumnType("int");

                    b.Property<bool>("is_deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("proctor_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("updated_by")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("proctor_id");

                    b.HasIndex("exam_session_id", "proctor_id")
                        .IsUnique()
                        .HasDatabaseName("IX_ProctorSession_Unique");

                    b.ToTable("ProctorSession", (string)null);
                });

            modelBuilder.Entity("ExamProctoring.Domain.Entities.Question", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("correct_answer")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("created_by")
                        .HasColumnType("int");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("deleted_by")
                        .HasColumnType("int");

                    b.Property<bool>("is_deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("marks")
                        .HasColumnType("int");

                    b.Property<string>("option_a")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("option_b")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("option_c")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("option_d")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("option_e")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("question_bank_id")
                        .HasColumnType("int");

                    b.Property<string>("question_text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("updated_by")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("question_bank_id");

                    b.ToTable("Question", (string)null);
                });

            modelBuilder.Entity("ExamProctoring.Domain.Entities.QuestionBank", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("authored_by_admin_id")
                        .HasColumnType("int");

                    b.Property<string>("course_code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("created_by")
                        .HasColumnType("int");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("deleted_by")
                        .HasColumnType("int");

                    b.Property<bool>("is_deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("locked_at")
                        .HasColumnType("datetime2");

                    b.Property<bool>("option_shuffle")
                        .HasColumnType("bit");

                    b.Property<bool>("randomization")
                        .HasColumnType("bit");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("updated_by")
                        .HasColumnType("int");

                    b.Property<string>("version")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("id");

                    b.HasIndex("authored_by_admin_id");

                    b.ToTable("QuestionBank", (string)null);
                });

            modelBuilder.Entity("ExamProctoring.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("created_by")
                        .HasColumnType("int");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("deleted_by")
                        .HasColumnType("int");

                    b.Property<DateTime>("expires_at")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("bit");

                    b.Property<string>("replaced_by_token")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("revoked_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("updated_by")
                        .HasColumnType("int");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("token")
                        .IsUnique();

                    b.HasIndex("user_id");

                    b.ToTable("RefreshToken", (string)null);
                });

            modelBuilder.Entity("ExamProctoring.Domain.Entities.Role", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("created_by")
                        .HasColumnType("int");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("deleted_by")
                        .HasColumnType("int");

                    b.Property<bool>("is_deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("updated_by")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("name")
                        .IsUnique();

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("ExamProctoring.Domain.Entities.Student", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("created_by")
                        .HasColumnType("int");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("deleted_by")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("face_id")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("failed_login_attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("is_active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("is_deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("lockout_end_utc")
                        .HasColumnType("datetime2");

                    b.Property<string>("middle_name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("phone_number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("photo_url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte[]>("reference_face_embedding")
                        .HasColumnType("varbinary(512)");

                    b.Property<DateTime?>("reference_face_generated_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("reference_face_model")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("reference_face_model_version")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("university_number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("updated_by")
                        .HasColumnType("int");

                    b.Property<string>("user_name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id");

                    b.HasIndex("email")
                        .IsUnique();

                    b.HasIndex("university_number")
                        .IsUnique();

                    b.HasIndex("user_name")
                        .IsUnique();

                    b.ToTable("Student", null, t =>
                        {
                            t.HasCheckConstraint("CK_Student_reference_face_embedding_length", "[reference_face_embedding] IS NULL OR DATALENGTH([reference_face_embedding]) = 512");
                        });
                });

            modelBuilder.Entity("ExamProctoring.Domain.Entities.StudentAnswer", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime?>("client_answered_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("created_by")
                        .HasColumnType("int");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("deleted_by")
                        .HasColumnType("int");

                    b.Property<int>("duration_ms")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("is_deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("question_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("saved_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("student_response")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("student_session_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("updated_by")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("question_id");

                    b.HasIndex("student_session_id", "question_id")
                        .IsUnique();

                    b.ToTable("StudentAnswer", (string)null);
                });

            modelBuilder.Entity("ExamProctoring.Domain.Entities.StudentLoginAttempt", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("created_by")
                        .HasColumnType("int");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("deleted_by")
                        .HasColumnType("int");

                    b.Property<int>("failed_attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("identifier_hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("is_deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("lockout_end_utc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("updated_by")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("identifier_hash")
                        .IsUnique();

                    b.ToTable("StudentLoginAttempt", (string)null);
                });

            modelBuilder.Entity("ExamProctoring.Domain.Entities.StudentSession", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("answered_count")
                        .HasColumnType("int");

                    b.Property<int?>("awarded_marks")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("created_by")
                        .HasColumnType("int");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("deleted_by")
                        .HasColumnType("int");

                    b.Property<string>("device_id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime?>("ends_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("exam_session_id")
                        .HasColumnType("int");

                    b.Property<bool>("face_match_passed")
                        .HasColumnType("bit");

                    b.Property<int>("failed_auth_attempts")
                        .HasColumnType("int");

                    b.Property<string>("finalisation_reason")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("finalised_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("graded_at_utc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("liveness_passed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("login_at")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("public_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<int?>("question_count")
                        .HasColumnType("int");

                    b.Property<string>("receipt_code")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("started_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("student_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("submitted_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("updated_by")
                        .HasColumnType("int");

                    b.Property<DateTime?>("verified_at")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("public_id")
                        .IsUnique();

                    b.HasIndex("receipt_code")
                        .IsUnique()
                        .HasFilter("[receipt_code] IS NOT NULL");

                    b.HasIndex("student_id");

                    b.HasIndex("exam_session_id", "student_id")
                        .IsUnique();

                    b.HasIndex("status", "ends_at");

                    b.ToTable("StudentSession", (string)null);
                });

            modelBuilder.Entity("ExamProctoring.Domain.Entities.SystemSettings", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("ambient_audio_monitoring")
                        .HasColumnType("bit");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("created_by")
                        .HasColumnType("int");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("deleted_by")
                        .HasColumnType("int");

                    b.Property<int>("face_match_threshold")
                        .HasColumnType("int");

                    b.Property<string>("face_sensitivity")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("gaze_alert_threshold_sec")
                        .HasColumnType("int");

                    b.Property<int>("grace_period_minutes")
                        .HasColumnType("int");

                    b.Property<bool>("is_deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("login_window_minutes")
                        .HasColumnType("int");

                    b.Property<int>("max_liveness_attempts")
                        .HasColumnType("int");

                    b.Property<int>("max_warnings_before_termination")
                        .HasColumnType("int");

                    b.Property<bool>("option_shuffle")
                        .HasColumnType("bit");

                    b.Property<bool>("question_randomisation")
                        .HasColumnType("bit");

                    b.Property<double?>("sface_cosine_threshold")
                        .HasColumnType("float");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("updated_by")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("SystemSettings", (string)null);
                });

            modelBuilder.Entity("ExamProctoring.Domain.Entities.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("created_by")
                        .HasColumnType("int");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("deleted_by")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("full_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<bool>("is_deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("password_hash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone_number")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("reset_otp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("reset_otp_expires_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("updated_by")
                        .HasColumnType("int");

                    b.Property<string>("user_name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id");

                    b.HasIndex("email")
                        .IsUnique();

                    b.HasIndex("user_name")
                        .IsUnique()
                        .HasFilter("[user_name] IS NOT NULL");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("ExamProctoring.Domain.Entities.User_Roles", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("created_by")
                        .HasColumnType("int");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("deleted_by")
                        .HasColumnType("int");

                    b.Property<bool>("is_deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("role_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("updated_by")
                        .HasColumnType("int");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("role_id");

                    b.HasIndex("user_id");

                    b.ToTable("User_Roles", (string)null);
                });

            modelBuilder.Entity("ExamProctoring.Domain.Entities.WarningMessage", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime?>("acknowledged_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("created_by")
                        .HasColumnType("int");

                    b.Property<DateTime?>("deleted_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("deleted_by")
                        .HasColumnType("int");

                    b.Property<bool>("is_deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("message_text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("proctor_action_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("sent_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("student_session_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("updated_by")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("proctor_action_id");

                    b.HasIndex("student_session_id");

                    b.ToTable("WarningMessage", (string)null);
                });

            modelBuilder.Entity("ExamProctoring.Domain.Entities.AlertEvent", b =>
                {
                    b.HasOne("ExamProctoring.Domain.Entities.MonitoringEvent", "MonitoringEvent")
                        .WithMany("AlertEvents")
                        .HasForeignKey("monitoring_event_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ExamProctoring.Domain.Entities.StudentSession", "StudentSession")
                        .WithMany("Alerts")
                        .HasForeignKey("student_session_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonitoringEvent");

                    b.Navigation("StudentSession");
                });

            modelBuilder.Entity("ExamProctoring.Domain.Entities.AttemptQuestion", b =>
                {
                    b.HasOne("ExamProctoring.Domain.Entities.Question", "Question")
                        .WithMany()
                        .HasForeignKey("question_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ExamProctoring.Domain.Entities.StudentSession", "StudentSession")
                        .WithMany("AttemptQuestions")
                        .HasForeignKey("student_session_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("StudentSession");
                });

            modelBuilder.Entity("ExamProctoring.Domain.Entities.AttemptQuestionOption", b =>
                {
                    b.HasOne("ExamProctoring.Domain.Entities.AttemptQuestion", "AttemptQuestion")
                        .WithMany("Options")
                        .HasForeignKey("attempt_question_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttemptQuestion");
                });

            modelBuilder.Entity("ExamProctoring.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("ExamProctoring.Domain.Entities.ExamSession", "ExamSession")
                        .WithMany("AuditLogs")
                        .HasForeignKey("exam_session_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExamSession");
                });

            modelBuilder.Entity("ExamProctoring.Domain.Entities.AutoScore", b =>
                {
                    b.HasOne("ExamProctoring.Domain.Entities.Question", "Question")
                        .WithMany("AutoScores")
                        .HasForeignKey("question_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ExamProctoring.Domain.Entities.StudentSession", "StudentSession")
                        .WithMany("AutoScores")
                        .HasForeignKey("student_session_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("StudentSession");
                });

            modelBuilder.Entity("ExamProctoring.Domain.Entities.ConnectivityBuffer", b =>
                {
                    b.HasOne("ExamProctoring.Domain.Entities.StudentSession", "StudentSession")
                        .WithMany("ConnectivityBuffers")
                        .HasForeignKey("student_session_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentSession");
                });

            modelBuilder.Entity("ExamProctoring.Domain.Entities.DeviceCheck", b =>
                {
                    b.HasOne("ExamProctoring.Domain.Entities.StudentSession", "StudentSession")
                        .WithMany()
                        .HasForeignKey("student_session_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentSession");
                });

            modelBuilder.Entity("ExamProctoring.Domain.Entities.DeviceCheckRequirement", b =>
                {
                    b.HasOne("ExamProctoring.Domain.Entities.DeviceCheck", "DeviceCheck")
                        .WithMany("Requirements")
                        .HasForeignKey("device_check_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeviceCheck");
                });

            modelBuilder.Entity("ExamProctoring.Domain.Entities.ExamSession", b =>
                {
                    b.HasOne("ExamProctoring.Domain.Entities.User", "CreatedByAdmin")
                        .WithMany("ExamSessions")
                        .HasForeignKey("created_by_admin_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ExamProctoring.Domain.Entities.QuestionBank", "QuestionBank")
                        .WithMany("ExamSessions")
                        .HasForeignKey("question_bank_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByAdmin");

                    b.Navigation("QuestionBank");
                });

            modelBuilder.Entity("ExamProctoring.Domain.Entities.GradingExport", b =>
                {
                    b.HasOne("ExamProctoring.Domain.Entities.ExamSession", "ExamSession")
                        .WithMany("GradingExports")
                        .HasForeignKey("exam_session_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExamSession");
                });

            modelBuilder.Entity("ExamProctoring.Domain.Entities.IdempotencyRecord", b =>
                {
                    b.HasOne("ExamProctoring.Domain.Entities.StudentSession", null)
                        .WithMany()
                        .HasForeignKey("student_session_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExamProctoring.Domain.Entities.IdentityVerificationAttempt", b =>
                {
                    b.HasOne("ExamProctoring.Domain.Entities.IdentityVerificationSession", "IdentityVerificationSession")
                        .WithMany("Attempts")
                        .HasForeignKey("identity_verification_session_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdentityVerificationSession");
                });

            modelBuilder.Entity("ExamProctoring.Domain.Entities.IdentityVerificationSession", b =>
                {
                    b.HasOne("ExamProctoring.Domain.Entities.StudentSession", "StudentSession")
                        .WithMany()
                        .HasForeignKey("student_session_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("StudentSession");
                });

            modelBuilder.Entity("ExamProctoring.Domain.Entities.MonitoringEvent", b =>
                {
                    b.HasOne("ExamProctoring.Domain.Entities.StudentSession", "StudentSession")
                        .WithMany("MonitoringEvents")
                        .HasForeignKey("student_session_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentSession");
                });

            modelBuilder.Entity("ExamProctoring.Domain.Entities.PermissionRole", b =>
                {
                    b.HasOne("ExamProctoring.Domain.Entities.Permission", "Permission")
                        .WithMany("Permission_Roles")
                        .HasForeignKey("permission_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExamProctoring.Domain.Entities.Role", "Role")
                        .WithMany("PermissionRoles")
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ExamProctoring.Domain.Entities.ProctorAction", b =>
                {
                    b.HasOne("ExamProctoring.Domain.Entities.User", "Admin")
                        .WithMany("ProctorActions")
                        .HasForeignKey("admin_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ExamProctoring.Domain.Entities.AlertEvent", "AlertEvent")
                        .WithMany("ProctorActions")
                        .HasForeignKey("alert_event_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("AlertEvent");
                });

            modelBuilder.Entity("ExamProctoring.Domain.Entities.ProctorSession", b =>
                {
                    b.HasOne("ExamProctoring.Domain.Entities.ExamSession", "ExamSession")
                        .WithMany("ProctorSessions")
                        .HasForeignKey("exam_session_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExamProctoring.Domain.Entities.User", "Proctor")
                        .WithMany("ProctorSessions")
                        .HasForeignKey("proctor_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExamSession");

                    b.Navigation("Proctor");
                });

            modelBuilder.Entity("ExamProctoring.Domain.Entities.Question", b =>
                {
                    b.HasOne("ExamProctoring.Domain.Entities.QuestionBank", "QuestionBank")
                        .WithMany("Questions")
                        .HasForeignKey("question_bank_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("QuestionBank");
                });

            modelBuilder.Entity("ExamProctoring.Domain.Entities.QuestionBank", b =>
                {
                    b.HasOne("ExamProctoring.Domain.Entities.User", "Admin")
                        .WithMany("QuestionBanks")
                        .HasForeignKey("authored_by_admin_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("ExamProctoring.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("ExamProctoring.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ExamProctoring.Domain.Entities.StudentAnswer", b =>
                {
                    b.HasOne("ExamProctoring.Domain.Entities.Question", "Question")
                        .WithMany("StudentAnswers")
                        .HasForeignKey("question_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ExamProctoring.Domain.Entities.StudentSession", "StudentSession")
                        .WithMany("Answers")
                        .HasForeignKey("student_session_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("StudentSession");
                });

            modelBuilder.Entity("ExamProctoring.Domain.Entities.StudentSession", b =>
                {
                    b.HasOne("ExamProctoring.Domain.Entities.ExamSession", "ExamSession")
                        .WithMany("StudentSessions")
                        .HasForeignKey("exam_session_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ExamProctoring.Domain.Entities.Student", "Student")
                        .WithMany("StudentSessions")
                        .HasForeignKey("student_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExamSession");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ExamProctoring.Domain.Entities.User_Roles", b =>
                {
                    b.HasOne("ExamProctoring.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExamProctoring.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ExamProctoring.Domain.Entities.WarningMessage", b =>
                {
                    b.HasOne("ExamProctoring.Domain.Entities.ProctorAction", "ProctorAction")
                        .WithMany("WarningMessages")
                        .HasForeignKey("proctor_action_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ExamProctoring.Domain.Entities.StudentSession", "StudentSession")
                        .WithMany("WarningMessages")
                        .HasForeignKey("student_session_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProctorAction");

                    b.Navigation("StudentSession");
                });

            modelBuilder.Entity("ExamProctoring.Domain.Entities.AlertEvent", b =>
                {
                    b.Navigation("ProctorActions");
                });

            modelBuilder.Entity("ExamProctoring.Domain.Entities.AttemptQuestion", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("ExamProctoring.Domain.Entities.DeviceCheck", b =>
                {
                    b.Navigation("Requirements");
                });

            modelBuilder.Entity("ExamProctoring.Domain.Entities.ExamSession", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("GradingExports");

                    b.Navigation("ProctorSessions");

                    b.Navigation("StudentSessions");
                });

            modelBuilder.Entity("ExamProctoring.Domain.Entities.IdentityVerificationSession", b =>
                {
                    b.Navigation("Attempts");
                });

            modelBuilder.Entity("ExamProctoring.Domain.Entities.MonitoringEvent", b =>
                {
                    b.Navigation("AlertEvents");
                });

            modelBuilder.Entity("ExamProctoring.Domain.Entities.Permission", b =>
                {
                    b.Navigation("Permission_Roles");
                });

            modelBuilder.Entity("ExamProctoring.Domain.Entities.ProctorAction", b =>
                {
                    b.Navigation("WarningMessages");
                });

            modelBuilder.Entity("ExamProctoring.Domain.Entities.Question", b =>
                {
                    b.Navigation("AutoScores");

                    b.Navigation("StudentAnswers");
                });

            modelBuilder.Entity("ExamProctoring.Domain.Entities.QuestionBank", b =>
                {
                    b.Navigation("ExamSessions");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("ExamProctoring.Domain.Entities.Role", b =>
                {
                    b.Navigation("PermissionRoles");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("ExamProctoring.Domain.Entities.Student", b =>
                {
                    b.Navigation("StudentSessions");
                });

            modelBuilder.Entity("ExamProctoring.Domain.Entities.StudentSession", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("Answers");

                    b.Navigation("AttemptQuestions");

                    b.Navigation("AutoScores");

                    b.Navigation("ConnectivityBuffers");

                    b.Navigation("MonitoringEvents");

                    b.Navigation("WarningMessages");
                });

            modelBuilder.Entity("ExamProctoring.Domain.Entities.User", b =>
                {
                    b.Navigation("ExamSessions");

                    b.Navigation("ProctorActions");

                    b.Navigation("ProctorSessions");

                    b.Navigation("QuestionBanks");

                    b.Navigation("RefreshTokens");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
