using ExamProctoring.Application.Common;
using ExamProctoring.Application.Common.DTOs;
using ExamProctoring.Application.Common.Interfaces;
using ExamProctoring.Application.Features.Students.DTOs;
using ExamProctoring.Domain.Entities;
using System.IO.Compression;
using System.Text;

namespace ExamProctoring.Application.Features.Students.Services
{
    public class StudentService : IStudentService
    {
        private const string DefaultImportPassword = "DefaultPassword123!";

        private readonly IStudentRepository _studentRepository;
        private readonly IPasswordHasher _passwordHasher;
        private readonly ICloudinaryService _cloudinaryService;
        private readonly IReferenceFaceEmbeddingGenerator _referenceFaceEmbeddingGenerator;

        public StudentService(
            IStudentRepository studentRepository,
            IPasswordHasher passwordHasher,
            ICloudinaryService cloudinaryService,
            IReferenceFaceEmbeddingGenerator referenceFaceEmbeddingGenerator)
        {
            _studentRepository = studentRepository;
            _passwordHasher = passwordHasher;
            _cloudinaryService = cloudinaryService;
            _referenceFaceEmbeddingGenerator = referenceFaceEmbeddingGenerator;
        }

        public async Task<PagedResult<StudentDto>> GetAllStudentsAsync(int page, int pageSize)
        {
            var students = await _studentRepository.GetPagedAsync(page, pageSize);
            var totalCount = await _studentRepository.CountAsync();

            var items = students.Select(s => new StudentDto
            {
                Id = s.id,
                UserName = s.user_name,
                Email = s.email,
                PhoneNumber = s.phone_number,
                FirstName = s.first_name,
                MiddleName = s.middle_name,
                LastName = s.last_name,
                UniversityNumber = s.university_number
            }).ToList();

            return new PagedResult<StudentDto>
            {
                Items = items,
                TotalCount = totalCount,
                Page = page,
                PageSize = pageSize
            };
        }

        // The ZIP must contain:
        //   - One .csv file with header: university_number,first_name,middle_name,last_name,email,phone_number
        //   - Photo files named {university_number}.jpg / .jpeg / .png
        //
        // The trusted SFace reference embedding is generated by the backend from each of those
        // photos during this import. There is no sidecar file and no separate enrolment step:
        // the official administrative photo is the single source of truth for identity.
        public async Task<ImportStudentsCsvResponse> ImportStudentsFromCsvAsync(Stream importZipStream, int adminId)
        {
            var response = new ImportStudentsCsvResponse();

            if (importZipStream == null || importZipStream.Length == 0)
            {
                response.Results.Add(new StudentImportResult { IsSuccess = false, Message = "ZIP file is empty or invalid" });
                return response;
            }

            string? csvContent = null;
            var photos = new Dictionary<string, (byte[] Data, string Extension)>(StringComparer.OrdinalIgnoreCase);

            try
            {
                using var zip = new ZipArchive(importZipStream, ZipArchiveMode.Read, leaveOpen: true);

                foreach (var entry in zip.Entries)
                {
                    var ext = Path.GetExtension(entry.Name).ToLowerInvariant();

                    if (ext == ".csv" && csvContent == null)
                    {
                        using var reader = new StreamReader(entry.Open(), Encoding.UTF8);
                        csvContent = await reader.ReadToEndAsync();
                    }
                    else if (ext == ".jpg" || ext == ".jpeg" || ext == ".png")
                    {
                        var key = Path.GetFileNameWithoutExtension(entry.Name);
                        if (string.IsNullOrEmpty(key)) continue;

                        using var ms = new MemoryStream();
                        await entry.Open().CopyToAsync(ms);
                        photos[key] = (ms.ToArray(), ext);
                    }
                }
            }
            catch (Exception ex)
            {
                response.Results.Add(new StudentImportResult { IsSuccess = false, Message = $"Failed to read ZIP: {ex.Message}" });
                return response;
            }

            if (csvContent == null)
            {
                response.Results.Add(new StudentImportResult { IsSuccess = false, Message = "No CSV file found inside the ZIP" });
                return response;
            }

            if (photos.Count == 0)
            {
                response.Results.Add(new StudentImportResult { IsSuccess = false, Message = "No photo files found inside the ZIP" });
                return response;
            }

            var lines = csvContent.Split('\n', StringSplitOptions.RemoveEmptyEntries);

            for (int i = 1; i < lines.Length; i++) // skip header
            {
                var result = await ProcessStudentRowAsync(lines[i].TrimEnd('\r'), i + 1, photos, adminId);
                response.Results.Add(result);
                response.TotalRecords++;
                if (result.IsSuccess) response.SuccessfulImports++;
                else response.FailedImports++;
            }

            return response;
        }

        private async Task<StudentImportResult> ProcessStudentRowAsync(
            string line, int lineNumber,
            Dictionary<string, (byte[] Data, string Extension)> photos,
            int adminId)
        {
            try
            {
                var parts = ParseCsvLine(line);

                if (parts.Length < 4)
                    return Fail(lineNumber, null, "Insufficient columns. Expected: university_number,first_name,middle_name,last_name[,email,phone_number]");

                var universityNumber = parts[0].Trim();
                var firstName        = parts[1].Trim();
                var middleName       = parts[2].Trim();
                var lastName         = parts[3].Trim();
                var email            = parts.Length > 4 ? parts[4].Trim() : string.Empty;
                var phoneNumber      = parts.Length > 5 ? parts[5].Trim() : string.Empty;

                if (string.IsNullOrEmpty(universityNumber) || string.IsNullOrEmpty(firstName) || string.IsNullOrEmpty(lastName))
                    return Fail(lineNumber, universityNumber, "university_number, first_name, and last_name are required");

                if (!photos.TryGetValue(universityNumber, out var photo))
                    return Fail(lineNumber, universityNumber, $"Photo not found in ZIP (expected: {universityNumber}.jpg/png)");

                // Identity enrolment runs on the ORIGINAL photo bytes, BEFORE the Cloudinary
                // upload. Two reasons for that order: the bytes are already in hand so nothing
                // is downloaded again, and a photo that cannot enrol never becomes an orphan
                // asset - uploads are never overwritten, so a failed row would otherwise leave
                // an image nobody can reach.
                var enrollment = _referenceFaceEmbeddingGenerator.Generate(photo.Data);

                if (!enrollment.IsSuccess)
                    return Fail(lineNumber, universityNumber,
                        $"Identity enrolment failed: {enrollment.FailureReason}");

                using var photoStream = new MemoryStream(photo.Data);
                var (uploadSuccess, photoUrl, uploadError) =
                    await _cloudinaryService.UploadImageAsync(photoStream, $"{universityNumber}{photo.Extension}");

                if (!uploadSuccess)
                    return Fail(lineNumber, universityNumber, $"Cloudinary upload failed: {uploadError}");

                var fullName = $"{firstName} {middleName} {lastName}".Replace("  ", " ").Trim();

                var existing = await _studentRepository.GetByUniversityNumberAsync(universityNumber);

                if (existing != null)
                {
                    existing.first_name  = firstName;
                    existing.middle_name = middleName;
                    existing.last_name   = lastName;
                    existing.photo_url   = photoUrl;
                    if (!string.IsNullOrEmpty(email))       existing.email        = email;
                    if (!string.IsNullOrEmpty(phoneNumber)) existing.phone_number = phoneNumber;
                    existing.updated_at = DateTime.UtcNow;
                    existing.updated_by = adminId;

                    // Photo and reference always move together. Re-importing an existing
                    // student is therefore also the backfill path: the new photo is stored and
                    // its embedding is regenerated in the same operation, so the two can never
                    // describe different images.
                    ApplyReferenceFace(existing, enrollment.Embedding!);

                    await _studentRepository.UpdateAsync(existing);

                    return new StudentImportResult
                    {
                        StudentId = existing.id,
                        UniversityNumber = universityNumber,
                        FullName = fullName,
                        Email = existing.email,
                        PhoneNumber = existing.phone_number,
                        PhotoUrl = photoUrl,
                        IsSuccess = true,
                        Message = "Updated existing student",
                        IdentityEnrollment = IdentityEnrollmentStatuses.Enrolled
                    };
                }
                else
                {
                    var resolvedEmail = string.IsNullOrEmpty(email)
                        ? $"{universityNumber.Replace("-", "")}@student.vu.edu".ToLower()
                        : email;

                    var student = new Student
                    {
                        university_number = universityNumber,
                        first_name        = firstName,
                        middle_name       = middleName,
                        last_name         = lastName,
                        email             = resolvedEmail,
                        phone_number      = phoneNumber,
                        user_name         = universityNumber,
                        password          = _passwordHasher.Hash(DefaultImportPassword),
                        photo_url         = photoUrl,
                        face_id           = string.Empty,
                        created_at        = DateTime.UtcNow,
                        created_by        = adminId
                    };

                    // Enrolment already succeeded above, otherwise this row would have failed
                    // before the upload. A created student therefore always has a reference.
                    ApplyReferenceFace(student, enrollment.Embedding!);

                    await _studentRepository.AddAsync(student);

                    return new StudentImportResult
                    {
                        StudentId = student.id,
                        UniversityNumber = universityNumber,
                        FullName = fullName,
                        Email = resolvedEmail,
                        PhoneNumber = phoneNumber,
                        PhotoUrl = photoUrl,
                        IsSuccess = true,
                        Message = "Created new student",
                        IdentityEnrollment = IdentityEnrollmentStatuses.Enrolled
                    };
                }
            }
            catch (Exception ex)
            {
                return Fail(lineNumber, null, ex.InnerException?.Message ?? ex.Message);
            }
        }

        private static StudentImportResult Fail(int lineNumber, string? universityNumber, string reason) =>
            new() { IsSuccess = false, UniversityNumber = universityNumber ?? string.Empty, Message = $"Line {lineNumber}: {reason}" };

        /// Writes the trusted reference identity produced by the backend generator.
        ///
        /// The model and version are stamped from the pinned constants rather than from
        /// anything in the request: this backend only ever produces SFace 2021dec vectors, and
        /// recording anything else would let an incompatible reference look enrolled.
        ///
        /// The vector arrives already L2-normalised and in storage form, so a comparison can
        /// never accidentally run against an unnormalised reference.
        private static void ApplyReferenceFace(Student student, byte[] embedding)
        {
            student.reference_face_embedding = embedding;
            student.reference_face_model = FaceEmbedding.Model;
            student.reference_face_model_version = FaceEmbedding.ModelVersion;
            student.reference_face_generated_at = DateTime.UtcNow;
        }

        private string[] ParseCsvLine(string line)
        {
            var result = new List<string>();
            var current = new StringBuilder();
            bool inQuotes = false;

            foreach (char c in line)
            {
                if (c == '"')
                    inQuotes = !inQuotes;
                else if (c == ',' && !inQuotes)
                {
                    result.Add(current.ToString());
                    current.Clear();
                }
                else
                    current.Append(c);
            }

            result.Add(current.ToString());
            return result.ToArray();
        }
    }
}
